worker_processes  1;

events { worker_connections 1024; }

http {
  sendfile on;
  upstream doctor { server doctor-service:4001; }
  upstream admin  { server admin-service:4002; }
  upstream lab    { server lab-service:4003; }
  upstream pharm  { server pharmacy-service:4004; }

  server {
    listen 80;

    location /doctor/   { proxy_pass http://doctor; }
    location /admin/    { proxy_pass http://admin; }
    location /lab/      { proxy_pass http://lab; }
    location /pharmacy/ { proxy_pass http://pharm; }

    location /healthz {
      return 200 '{"ok":true}';
      add_header Content-Type application/json;
    }
  }
}
